In [1]:
1>2

False

In [2]:
1<2

True

In [3]:
1==2

False

In [4]:
1!=2

True

In [7]:
import numpy as np

In [9]:
a = np.array([True, True, False, False])
b = np.array([True, False, True, False])

In [10]:
a & b

array([ True, False, False, False])

In [11]:
a | b

array([ True,  True,  True, False])

In [12]:
~a

array([False, False,  True,  True])

In [13]:
a = np.array([[1, 2],
              [3, 4]])

b = np.array([[4, 2],
              [3, 1]])

# поэлементное сравнение
c = a >= b
print(c)

[[False  True]
 [ True  True]]


In [23]:
a=np.eye(2)
a

array([[1., 0.],
       [0., 1.]])

In [24]:
b = np.ones((2,2))
b

array([[1., 1.],
       [1., 1.]])

In [25]:
d = np.array([[1, 1],
            [1, 0]])
d

array([[1, 1],
       [1, 0]])

#### Пример 1

In [31]:
'd' in locals()

True

In [30]:
if 'd' in locals():
    c=a
else:
    c=b
print(c)

[[1. 0.]
 [0. 1.]]


#### Пример 2

In [39]:
a <= b

array([[ True,  True],
       [ True,  True]])

In [40]:
if (a <= b).all():
    c=a
else:
    c=b
print(c)

[[1. 0.]
 [0. 1.]]


In [44]:
if (a <= b).all():
    pass

In [45]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

for k in a.T:
    print(k)

[1 4]
[2 5]
[3 6]


In [47]:
p = 1
k = 0
while p < 10:
    p = p * 2
    k = k + 1
print(f'k = {k}, p = {p}')

k = 4, p = 16


In [49]:
a = np.array([2, 5, 3, 4, 5])
while a.any():
    a = a - 1
    if (a < 0).any():
        break
print(a)

[-1  2  0  1  2]


In [50]:
var = None

if var in {1, 2, 12, 'January', 'February', 'December'}:
    print('Winter')
elif var in {3, 4, 5, 'March', 'April', 'May'}:
    print('Spring')
elif var in {6, 7, 8, 'June', 'July', 'August'}:
    print('Summer')
elif var in {9, 10, 11, 'September', 'October', 'November'}:
    print('Autumn')
else:
    print('It is not a month.')


It is not a month.


### Пример из текста методички

Цикл `while` с условием `a.all()`: элементы уменьшаются, пока хотя бы один из них не станет равным нулю. С условием `a.any()` тот же цикл без `break` не завершится: элементы обнуляются в разные моменты.

In [ ]:
a = np.array([2, 5, 3, 4, 5])
while a.all():
    a = a - 1
print(a)    # [0 3 1 2 3]

### Пример из текста методички

Переключатель `match`–`case` (Python 3.10+).

In [ ]:
for var in [3, 'May', 10, 'Autumn']:
    match var:
        case 1 | 2 | 12 | 'January' | 'February' | 'December':
            print(var, '->', 'Winter')
        case 3 | 4 | 5 | 'March' | 'April' | 'May':
            print(var, '->', 'Spring')
        case 6 | 7 | 8 | 'June' | 'July' | 'August':
            print(var, '->', 'Summer')
        case 9 | 10 | 11 | 'September' | 'October' | 'November':
            print(var, '->', 'Autumn')
        case _:
            print(var, '->', 'It is not a month.')