## Справка: `dir` и `help`

`dir(math)` показывает список имён модуля, `help(print)` — описание функции.

In [1]:
import math

In [2]:
dir(math)

['__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'acos',
 'acosh',
 'asin',
 'asinh',
 'atan',
 'atan2',
 'atanh',
 'cbrt',
 'ceil',
 'comb',
 'copysign',
 'cos',
 'cosh',
 'degrees',
 'dist',
 'e',
 'erf',
 'erfc',
 'exp',
 'exp2',
 'expm1',
 'fabs',
 'factorial',
 'floor',
 'fmod',
 'frexp',
 'fsum',
 'gamma',
 'gcd',
 'hypot',
 'inf',
 'isclose',
 'isfinite',
 'isinf',
 'isnan',
 'isqrt',
 'lcm',
 'ldexp',
 'lgamma',
 'log',
 'log10',
 'log1p',
 'log2',
 'modf',
 'nan',
 'nextafter',
 'perm',
 'pi',
 'pow',
 'prod',
 'radians',
 'remainder',
 'sin',
 'sinh',
 'sqrt',
 'tan',
 'tanh',
 'tau',
 'trunc',
 'ulp']

In [3]:
help(print)

Help on built-in function print in module builtins:

print(*args, sep=' ', end='\n', file=None, flush=False)
    Prints the values to a stream, or to sys.stdout by default.
    
    sep
      string inserted between values, default a space.
    end
      string appended after the last value, default a newline.
    file
      a file-like object (stream); defaults to the current sys.stdout.
    flush
      whether to forcibly flush the stream.



## Векторы и матрицы NumPy

Обратите внимание: `u` задан вещественными числами, `v` — целыми. Посмотрите тип элементов (`u.dtype`, `v.dtype`) и тип результатов операций над ними.

In [2]:
import numpy as np

In [3]:
u = np.array([1.2, 2.3, 3.4])
v = np.array([4, 5, 6])

In [6]:
u, v

(array([1.2, 2.3, 3.4]), array([4, 5, 6]))

In [4]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [8]:
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Стандартные операции с векторами и матрицами

In [9]:
u+v

array([5.2, 7.3, 9.4])

Операции `*`, `/`, `//` выполняются **поэлементно** (в отличие от MATLAB, где `*` — матричное умножение).

In [10]:
u*v

array([ 4.8, 11.5, 20.4])

In [11]:
u/v

array([0.3       , 0.46      , 0.56666667])

In [12]:
u // 2

array([0., 1., 1.])

`np.dot` — скалярное произведение, `np.cross` — векторное (определено для векторов длины 2 и 3).

In [13]:
np.dot(u, v)

np.float64(36.7)

In [14]:
np.cross(u, v)

array([-3.2,  6.4, -3.2])

In [15]:
A.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

Матричное умножение — оператор `@`. Матрицы $A$ ($3\times 4$) и $B$ ($4\times 3$) можно перемножить в обоих порядках. Проверьте, что `A @ B != B @ A`: у произведений даже разные размеры (`(A @ B).shape` и `(B @ A).shape`).

In [14]:
# Матрица A размера 3 x 4
A = np.array([
    [1, 2, 3, 4],
    [0, 1, 0, 1],
    [5, 6, 7, 8]
])

# Матрица B размера 4 x 3
B = np.array([
    [1, 0, 2],
    [0, 1, 1],
    [1, 0, 0],
    [0, 1, 3]
])

# Матрица C размера 3 x 3 — результат A @ B
C = A @ B
C

array([[ 4,  6, 16],
       [ 0,  2,  4],
       [12, 14, 40]])

In [15]:
B@A

array([[11, 14, 17, 20],
       [ 5,  7,  7,  9],
       [ 1,  2,  3,  4],
       [15, 19, 21, 25]])

#### Решение систем уравнений

In [16]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
v = np.array([4, 5, 6])

**Внимание:** матрица $A$ здесь вырождена (строки линейно зависимы), но `np.linalg.solve` не выдаёт ошибку, а возвращает «решение»: из-за ошибок округления определитель получается не нулём, а величиной порядка $10^{-16}$. Проверьте `np.linalg.det(A)`, `np.linalg.matrix_rank(A)` и `np.linalg.cond(A)`: огромное число обусловленности — признак того, что ответу доверять нельзя.

In [17]:
np.linalg.solve(A, v)

array([-3.33333333,  3.66666667,  0.        ])

In [18]:
v

array([4, 5, 6])

Переопределённая система (4 уравнения, 2 неизвестных) решается в смысле наименьших квадратов. Обратите внимание: невязка `A @ X - B` не равна нулю — точного решения нет.

In [19]:
A = np.array([
    [1, 1],
    [2, 1],
    [3, 1],
    [4, 1]
])

# Вектор правой части
B = np.array([2.1, 2.9, 3.7, 4.2])

# Решение в смысле МНК
X, residuals, rank, s = np.linalg.lstsq(A, B, rcond=None)

print("Решение X =")
print(X)

# Проверим результат
print("Невязка AX - B =")
print(A @ X - B)

Решение X =
[0.71 1.45]
Невязка AX - B =
[ 0.06 -0.03 -0.12  0.09]


`A ** 2` — поэлементное возведение в квадрат. Сравните с матричной степенью `np.linalg.matrix_power(A, k)` в следующей ячейке.

In [20]:
A ** 2

array([[ 1,  1],
       [ 4,  1],
       [ 9,  1],
       [16,  1]])

In [21]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
np.linalg.matrix_power(A, 3)

array([[ 468,  576,  684],
       [1062, 1305, 1548],
       [1656, 2034, 2412]])

In [22]:
np.exp(v)

array([ 54.59815003, 148.4131591 , 403.42879349])

In [23]:
x = np.linspace(0, np.pi, 5)
y = np.sin(x)
y

array([0.00000000e+00, 7.07106781e-01, 1.00000000e+00, 7.07106781e-01,
       1.22464680e-16])

## Округление

Сравните результаты для отрицательного элемента $-3.4$: `floor` и `ceil` округляют к $-\infty$ и $+\infty$, `trunc` и `fix` — к нулю, `round` — к ближайшему целому.

In [24]:
x = np.array([ 2.7, -3.4, 1.51 ])

In [25]:
np.round(x)

array([ 3., -3.,  2.])

In [26]:
np.floor(x)

array([ 2., -4.,  1.])

In [27]:
np.ceil(x)

array([ 3., -3.,  2.])

In [28]:
np.trunc(x) 

array([ 2., -3.,  1.])

In [29]:
np.fix(x)

array([ 2., -3.,  1.])

У `np.remainder` знак результата совпадает со знаком **делителя** (как у `mod` в MATLAB): для $-3.4$ получится $1.6$. Сравните с `np.fmod(x, v)`, где знак совпадает со знаком делимого (как у `rem` в MATLAB).

In [30]:
np.remainder(x, v)

array([2.7 , 1.6 , 1.51])

In [31]:
x = np.array([12, 18, 27, 100])
y = np.array([8,  24, 9,  35])

g = np.gcd(x, y)
print("np.gcd(x, y) =", g)

np.gcd(x, y) = [4 6 9 5]


## Комплексные числа

In [32]:
z = 6.7 + 7.897j

In [33]:
np.angle(z)

np.float64(0.8672182422847324)

In [34]:
np.conj(z)

np.complex128(6.7-7.897j)

In [35]:
np.imag(z)

7.897

In [36]:
np.real(z)

6.7

Для комплексного числа `np.sign(z)` возвращает $z/|z|$ — проекцию на единичную окружность. Проверьте: `z / abs(z)`.

In [37]:
print(z)
np.sign(z)

(6.7+7.897j)


np.complex128(0.6469502275264093+0.7625322308620976j)

## Формирование матриц

In [38]:
np.zeros((4, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [39]:
np.ones((4, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [40]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Вектор `v` размещается на первой наддиагонали, поэтому матрица получается размера $(n+1)\times(n+1)$.

In [41]:
np.diag(v, 1)

array([[0, 4, 0, 0],
       [0, 0, 5, 0],
       [0, 0, 0, 6],
       [0, 0, 0, 0]])

Случайная матрица меняется при каждом запуске. Для воспроизводимости используйте генератор с зерном: `np.random.default_rng(1).random((4, 5))`. В следующих ячейках сравните исходную матрицу с результатами `fliplr`, `flipud`, `rot90`.

In [42]:
A = np.random.rand(4, 5)
A

array([[0.2460538 , 0.54508828, 0.23646676, 0.60931804, 0.31293162],
       [0.10264098, 0.86637318, 0.47082305, 0.41645905, 0.86654893],
       [0.3529874 , 0.60204384, 0.28752836, 0.98156622, 0.17456856],
       [0.04288072, 0.53982965, 0.70386761, 0.60923198, 0.76884315]])

In [43]:
np.fliplr(A)

array([[0.31293162, 0.60931804, 0.23646676, 0.54508828, 0.2460538 ],
       [0.86654893, 0.41645905, 0.47082305, 0.86637318, 0.10264098],
       [0.17456856, 0.98156622, 0.28752836, 0.60204384, 0.3529874 ],
       [0.76884315, 0.60923198, 0.70386761, 0.53982965, 0.04288072]])

In [44]:
np.flipud(A)

array([[0.04288072, 0.53982965, 0.70386761, 0.60923198, 0.76884315],
       [0.3529874 , 0.60204384, 0.28752836, 0.98156622, 0.17456856],
       [0.10264098, 0.86637318, 0.47082305, 0.41645905, 0.86654893],
       [0.2460538 , 0.54508828, 0.23646676, 0.60931804, 0.31293162]])

In [45]:
np.rot90(A, 2)

array([[0.76884315, 0.60923198, 0.70386761, 0.53982965, 0.04288072],
       [0.17456856, 0.98156622, 0.28752836, 0.60204384, 0.3529874 ],
       [0.86654893, 0.41645905, 0.47082305, 0.86637318, 0.10264098],
       [0.31293162, 0.60931804, 0.23646676, 0.54508828, 0.2460538 ]])

Без аргумента `axis` сумма берётся по **всем** элементам (в MATLAB `sum(A)` — по столбцам).

In [46]:
x = np.array([[1, 4, 7],
              [2, 5, 8],
              [3, 6, 9]])

print(f'np.sum(x)={np.sum(x)}')
print(f'np.sum(x, axis=0)={np.sum(x, axis=0)} -  сумма по столбцам')
print(f'np.sum(x, axis=1)={np.sum(x, axis=1)} - сумма по строкам')

np.sum(x)=45
np.sum(x, axis=0)=[ 6 15 24] -  сумма по столбцам
np.sum(x, axis=1)=[12 15 18] - сумма по строкам


In [47]:
x = np.array([1.0, 2.0, np.nan, 4.0, 5.0])
print("Исходный вектор:")
print(x)

# Обычная медиана — NaN "портит" вычисление
m1 = np.median(x)
print("\nnp.median(x) =", m1)

# Медиана, игнорирующая NaN
m2 = np.nanmedian(x)
print("np.nanmedian(x) =", m2)

Исходный вектор:
[ 1.  2. nan  4.  5.]

np.median(x) = nan
np.nanmedian(x) = 3.0


`np.gradient` возвращает производные вдоль оси 0 (по строкам) и оси 1 (по столбцам); по умолчанию шаг сетки равен 1.

In [48]:
Px, Py = np.gradient(A)
Px, Py

(array([[-0.14341282,  0.3212849 ,  0.23435629, -0.19285898,  0.55361731],
        [ 0.0534668 ,  0.02847778,  0.0255308 ,  0.18612409, -0.06918153],
        [-0.02988013, -0.16327176,  0.11652228,  0.09638646, -0.04885289],
        [-0.31010668, -0.06221418,  0.41633925, -0.37233424,  0.59427459]]),
 array([[ 0.29903448, -0.00479352,  0.03211488,  0.03823243, -0.29638642],
        [ 0.7637322 ,  0.18409104, -0.22495706,  0.19786294,  0.45008987],
        [ 0.24905644, -0.03272952,  0.18976119, -0.0564799 , -0.80699766],
        [ 0.49694894,  0.33049345,  0.03470116,  0.03248777,  0.15961116]]))

In [49]:
# Задаём сетку x и значения функции y = x^2
x = np.linspace(0, 3, 7)       # точки: 0, 0.5, 1.0, ..., 3.0
y = x**2

print("x =", x)
print("y =", y)

# Интеграл y(x) методом трапеций
I = np.trapezoid(y, x)

print("\nИнтеграл np.trapezoid(y, x) =", I)

# Для сравнения точное значение ∫ x^2 dx от 0 до 3 = 9
print("Точное значение =", 9)

x = [0.  0.5 1.  1.5 2.  2.5 3. ]
y = [0.   0.25 1.   2.25 4.   6.25 9.  ]

Интеграл np.trapezoid(y, x) = 9.125
Точное значение = 9


## Нормы векторов и матриц

In [50]:
# Определим вектор
v = np.array([3, -4, 12])
print("v =", v)

v = [ 3 -4 12]


In [51]:
# Евклидова норма (по умолчанию 2-норма)
n2 = np.linalg.norm(v)
print("\n2-норма:", n2)


2-норма: 13.0


In [52]:
# 1-норма
n1 = np.linalg.norm(v, ord=1)
print("1-норма:", n1)

1-норма: 19.0


In [53]:
# Бесконечная норма
n_inf = np.linalg.norm(v, ord=np.inf)
print("Бесконечная норма:", n_inf)

Бесконечная норма: 12.0


In [54]:
# Норма с показателем -∞ (минимум модулей)
n_min = np.linalg.norm(v, ord=-np.inf)
print("(-∞)-норма:", n_min)

(-∞)-норма: 3.0


Нормы матрицы: сравните 2-норму (наибольшее сингулярное число), 1-норму (наибольшая сумма модулей по столбцам) и $\infty$-норму (наибольшая сумма модулей по строкам).

In [55]:
np.linalg.norm(A, ord=2)

np.float64(2.328864319328597)

In [56]:
np.linalg.norm(A, ord=1)

np.float64(2.616575289507807)

In [57]:
np.linalg.norm(A, ord = np.inf)

np.float64(2.7228451810545713)

In [58]:
np.linalg.norm(A, ord = -np.inf)

np.float64(1.9498584884327712)

In [59]:
np.linalg.norm(A, ord = 'fro')

np.float64(2.47074396796741)

In [60]:
A.shape

(4, 5)

In [61]:
A.size

20

## Характеристики квадратной матрицы

Проверьте на этой матрице: `np.trace(A)` равен сумме собственных чисел, `np.linalg.det(A)` — их произведению, а `A @ np.linalg.inv(A)` близко к единичной матрице (`np.allclose(..., np.eye(4))`).

In [62]:
A = np.random.rand(4, 4)
A

array([[0.22522418, 0.8894652 , 0.99516503, 0.54530544],
       [0.00969953, 0.14228794, 0.92347392, 0.40246663],
       [0.87854474, 0.76239916, 0.17536357, 0.08273708],
       [0.19618762, 0.41298111, 0.07967752, 0.0488982 ]])

In [63]:
np.linalg.det(A)

np.float64(-0.015355156239144812)

In [64]:
np.trace(A)

np.float64(0.5917738816172977)

In [65]:
 np.linalg.inv(A)

array([[  0.47475972,  -0.50142042,   2.06181406,  -4.65605192],
       [ -0.67315871,   0.43898893,  -1.12800706,   5.8023963 ],
       [ -5.34366808,   6.07050941,  -1.36134878,  11.93066125],
       [ 12.48778199, -11.58743623,   3.4727681 , -29.31449006]])

In [66]:
np.linalg.pinv(A)

array([[  0.47475972,  -0.50142042,   2.06181406,  -4.65605192],
       [ -0.67315871,   0.43898893,  -1.12800706,   5.8023963 ],
       [ -5.34366808,   6.07050941,  -1.36134878,  11.93066125],
       [ 12.48778199, -11.58743623,   3.4727681 , -29.31449006]])

In [67]:
import scipy
scipy.linalg.sqrtm(A)

array([[0.38970396+0.45335864j, 0.57822734-0.25009174j,
        0.6023056 -0.28609729j, 0.29197678-0.22391144j],
       [0.22296699+0.12069153j, 0.33082962+0.47309993j,
        0.34460586-0.41607518j, 0.16705292-0.12285111j],
       [0.33260361-0.42589513j, 0.49350411-0.1655601j ,
        0.51405436+0.54604018j, 0.24919565+0.18493067j],
       [0.11502969+0.03444185j, 0.17067651-0.26159545j,
        0.17778373+0.07944548j, 0.08618336+0.16066437j]])

In [68]:
scipy.linalg.expm(A)

array([[2.1623516 , 2.18212881, 2.30412821, 1.16986404],
       [0.65364515, 1.94476558, 1.52638123, 0.6949656 ],
       [1.47890654, 1.84449227, 2.49995068, 0.73280224],
       [0.40675826, 0.76430669, 0.5498494 , 1.27328394]])

In [69]:
scipy.linalg.logm(A)

array([[-0.39214643+2.21464104j,  0.64035535-1.3753742j ,
         0.73373065-1.43264685j, -0.14913451-0.69449731j],
       [ 0.77411842-0.53035031j, -0.47631223+2.35467981j,
        -0.33907046-0.81968108j,  0.35961908-0.39735284j],
       [-0.60593157-0.79113248j,  0.99946597-1.17385112j,
         0.02958421+1.9188606j ,  1.63885875-0.59273792j],
       [ 0.9829693 -0.27361014j, -0.87120678-0.40597192j,
         0.77898423-0.4228772j , -3.3374295 +2.93659651j]])

In [70]:
np.poly(A)

array([ 1.        , -0.59177388, -1.74372515, -0.45700154, -0.01535516])

In [71]:
np.linalg.eig(A)

EigResult(eigenvalues=array([ 1.74443682, -0.85106445, -0.26214398, -0.03945451]), eigenvectors=array([[-0.68312323, -0.15078213,  0.50169587,  0.18497511],
       [-0.39084523, -0.70295932, -0.66353638, -0.21158108],
       [-0.5830304 ,  0.62701777,  0.04421524, -0.34978583],
       [-0.20163883,  0.2999361 ,  0.55323209,  0.89368201]]))

In [72]:
np.linalg.eigvals(A)

array([ 1.74443682, -0.85106445, -0.26214398, -0.03945451])

`svd` возвращает $U$, вектор сингулярных чисел $S$ и **уже транспонированную** матрицу $V^T$. Проверьте: `U @ np.diag(S) @ Vh` совпадает с $A$.

In [73]:
np.linalg.svd(A)

SVDResult(U=array([[-0.74984931, -0.20657281,  0.51667056, -0.3579179 ],
       [-0.4276419 , -0.57081172, -0.61133587,  0.34287728],
       [-0.46374213,  0.75865789, -0.4446211 , -0.10813658],
       [-0.19947847,  0.23651608,  0.4020349 ,  0.86176356]]), S=array([1.91508143, 1.00744401, 0.29999781, 0.02652943]), Vh=array([[-0.3235296 , -0.60767682, -0.64663432, -0.32851413],
       [ 0.65597157,  0.40808011, -0.57652614, -0.26606302],
       [-0.67103231,  0.6654343 , -0.32106055,  0.06191082],
       [-0.12143117,  0.14627607,  0.38262488, -0.90413273]]))

In [74]:
np.linalg.matrix_rank(A)

np.int64(4)

In [75]:
np.linalg.cond(A)

np.float64(72.1870429570962)

In [76]:
scipy.linalg.matrix_balance(A, separate=True)

(array([[0.22522418, 0.8894652 , 0.99516503, 0.54530544],
        [0.00969953, 0.14228794, 0.92347392, 0.40246663],
        [0.87854474, 0.76239916, 0.17536357, 0.08273708],
        [0.19618762, 0.41298111, 0.07967752, 0.0488982 ]]),
 (array([1., 1., 1., 1.]), array([0, 1, 2, 3])))

In [77]:
scipy.linalg.null_space(A)

array([], shape=(4, 0), dtype=float64)

In [78]:
np.linalg.qr(A)

QRResult(Q=array([[-0.2427032 , -0.89701929,  0.04693745, -0.36639928],
       [-0.01045228, -0.18429411, -0.92213789,  0.33998257],
       [-0.94672613,  0.29330035, -0.08545358, -0.10189317],
       [-0.21141319, -0.27453048,  0.37437452,  0.86010534]]), R=array([[-0.92798193, -1.02645614, -0.43404829, -0.22522115],
       [ 0.        , -0.71385423, -1.03331274, -0.55247896],
       [ 0.        ,  0.        , -0.79001599, -0.33429842],
       [ 0.        ,  0.        ,  0.        , -0.02934062]]))

In [79]:
scipy.linalg.lu(A)

(array([[0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [1., 0., 0., 0.],
        [0., 0., 0., 1.]]),
 array([[ 1.        ,  0.        ,  0.        ,  0.        ],
        [ 0.25636051,  1.        ,  0.        ,  0.        ],
        [ 0.01104045,  0.19289278,  1.        ,  0.        ],
        [ 0.22330976,  0.3497468 , -0.39528016,  1.        ]]),
 array([[ 0.87854474,  0.76239916,  0.17536357,  0.08273708],
        [ 0.        ,  0.69401616,  0.95020873,  0.52409492],
        [ 0.        ,  0.        ,  0.73824942,  0.30045905],
        [ 0.        ,  0.        ,  0.        , -0.03411282]]))

## Обусловленность

In [80]:
A = scipy.linalg.hilbert(6)
B = A.copy()
B[0, 5] *= 1.01   # изменение на 1%
B

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
        0.16833333],
       [0.5       , 0.33333333, 0.25      , 0.2       , 0.16666667,
        0.14285714],
       [0.33333333, 0.25      , 0.2       , 0.16666667, 0.14285714,
        0.125     ],
       [0.25      , 0.2       , 0.16666667, 0.14285714, 0.125     ,
        0.11111111],
       [0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
        0.1       ],
       [0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ,
        0.09090909]])

Относительное изменение элементов обратной матрицы при изменении одного элемента $A$ на 1%. Найдите наибольшее значение `np.abs(result).max()` и сравните с числом обусловленности.

In [81]:
result = (np.linalg.inv(B) - np.linalg.inv(A)) / np.linalg.inv(A)
result

array([[-1.27624309, -2.1878453 , -2.87154696, -3.40331492, -3.82872928,
        -4.17679558],
       [-1.27624309, -1.64088398, -1.91436464, -2.12707182, -2.29723757,
        -2.43646409],
       [-1.27624309, -1.45856354, -1.59530387, -1.70165746, -1.78674033,
        -1.85635359],
       [-1.27624309, -1.36740331, -1.43577348, -1.48895028, -1.53149171,
        -1.56629834],
       [-1.27624309, -1.31270718, -1.34005525, -1.36132597, -1.37834254,
        -1.39226519],
       [-1.27624309, -1.27624309, -1.27624309, -1.27624309, -1.27624309,
        -1.27624309]])

In [82]:
wA, _ = np.linalg.eig(A)
wB, _ = np.linalg.eig(B)
print(wA, '\n', wB)
d = np.linalg.cond(A)
print(d)

[1.61889986e+00 2.42360871e-01 1.63215213e-02 6.15748354e-04
 1.25707571e-05 1.08279948e-07] 
 [ 1.61912623e+00  2.41980988e-01  1.65225969e-02  5.59491693e-04
  2.16154855e-05 -2.48179287e-07]
14951058.640168244


**Замечание.** Функция `moler` ниже **не** воспроизводит матрицу `gallery(5)` из MATLAB. Правильный пример с `gallery(5)` приведён в конце ноутбука (пример из текста методички).

In [90]:
# > a=gallery(5) нет
# но можно сделать так

import numpy as np

def moler(n: int) -> np.ndarray:
    A = np.empty((n, n), dtype=float)
    for i in range(n):
        for j in range(n):
            if i == j:
                A[i, j] = i + 1
            else:
                A[i, j] = min(i, j) - 1
    return A
A = moler(5)
A

array([[ 1., -1., -1., -1., -1.],
       [-1.,  2.,  0.,  0.,  0.],
       [-1.,  0.,  3.,  1.,  1.],
       [-1.,  0.,  1.,  4.,  2.],
       [-1.,  0.,  1.,  2.,  5.]])

In [91]:
# Копируем матрицу
B = A.copy()

# Возмущаем один элемент на 1%: аналог b(5,1) = b(5,1)*1.01 в MATLAB
# В Python индексация с нуля: (5,1) -> [4,0]
B[4, 0] *= 1.01

# Собственные значения
eig_A = np.linalg.eigvals(A)
eig_B = np.linalg.eigvals(B)

print("Собственные значения матрицы A:")
print(eig_A)

print("\nСобственные значения матрицы B:")
print(eig_B)

# Число обусловленности
cond_A = np.linalg.cond(A)

print("\nЧисло обусловленности cond(A):")
print(cond_A)

Собственные значения матрицы A:
[7.48749993 0.00864627 2.82893478 2.39646853 2.27845048]

Собственные значения матрицы B:
[7.48928775 0.00795544 2.82711158 2.39747418 2.27817105]

Число обусловленности cond(A):
865.9801223928374


### Пример из текста методички

Раздел «Нормы векторов и матриц» → пример с матрицей `gallery(5)`.

В NumPy и SciPy аналога `gallery(5)` нет, поэтому матрица задаётся явно. Она нильпотентна ($a^5 = 0$), т.е. все её собственные числа в точной арифметике равны нулю. Обратите внимание, насколько сильно меняются вычисленные собственные числа при изменении одного элемента на 1%.

In [ ]:
import numpy as np

# матрица gallery(5) из MATLAB, заданная явно
a = np.array([[  -9,    11,   -21,     63,   -252],
              [  70,   -69,   141,   -421,   1684],
              [-575,   575, -1149,   3451, -13801],
              [3891, -3891,  7782, -23345,  93365],
              [1024, -1024,  2048,  -6144,  24572]], dtype=float)

# проверка нильпотентности в целочисленной арифметике: a^5 = 0
print("max |a^5| =", np.abs(np.linalg.matrix_power(a.astype(int), 5)).max())

# возмущение одного элемента на 1%: b(5,1) в MATLAB -> b[4, 0] в Python
b = a.copy()
b[4, 0] *= 1.01

print("собственные числа a:", np.linalg.eigvals(a))
print("собственные числа b:", np.linalg.eigvals(b))
print("cond(a) =", np.linalg.cond(a))